### ISSUE TITLE
Filepath to access srv/imars-objects/gom

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/python-tech-workgroup#13]
How should I arrange the filepath to get to the raw L2 files here:
/srv/imars-objects/gom/L2_MODA_r2018/OC

**Comment by 7yl4r** [comment]
I am going to close this issue since we discussed it today. We can revist how to use `wget` or `curl` after #14 

The streaming data solution would be great but it isn't clear to me how difficult it is going to be.
