### ISSUE TITLE
Project Idea: Eddy and Argo float data in the SO

### ISSUE THREAD

**Issue by sbartoloni** [USF-IMARS/python-tech-workgroup#29]
My goal is to find "interesting" instances of an Argo float passing through an eddy in the Southern Ocean. This could include the float passing an eddy in a frontal region or the float staying within the eddy for multiple sampling periods. I also want to make sure the float has pH/DIC data.

Data Sources: 
Argo Floats: https://soccompu.princeton.edu/www/index.html
Mesoscale eddy trajectories: https://www.aviso.altimetry.fr/en/data/products/value-added-products/global-mesoscale-eddy-trajectory-product.html

**Comment by 7yl4r** [comment]
I would like to walk through setting up a project repository for this on Friday. It will go something like this:

1. create new repo
2. set up mybinder.org config
3. create new .ipynb
4. download a .zip from your link above
5. unzip the file 
6. load the data into python

For 4 & 5 we could use the bash CLI utilities `wget` and `uzip` or we could do it in python. Does this sound like a good plan?

**Comment by sbartoloni** [comment]
Here is the link to the repo I created our on lab GitHub 

https://github.com/Williams-OBGC-Lab/SOCCOM_eddy
