### ISSUE TITLE
Issue from B. Rosenheim

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/python-tech-workgroup#37]
Issue from Brad Rosenheim:

![IMG_07B2F1CE93CB-1](https://user-images.githubusercontent.com/26553741/163407977-53cb7954-64cf-43e0-9d4d-3077a320bb01.jpeg)

**Comment by 7yl4r** [comment]
I think we emailed about this. Unfortunately this is a VSCode issue nd I don't really have knowledge about that. I used VS a long time back but didn't like it.
