### ISSUE TITLE
are there IMaRS-external people we should invite?

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/python-tech-workgroup#5]
Although the projects we focus on here are driven by IMaRS's goals, others at CMS or elsewhere may benefit from the python, git, github basics. 

I want to use this issue to brainstorm on who we might consider inviting from outside IMaRS. 
We probably want to keep this group under 10 people but I think 3 is too small.

Do you know anyone interested in learning python?

Any potential collaborators interested in the projects we are pursuing here?

Please share your thoughts.

**Comment by 7yl4r** [comment]
I have had some discussions with Nancy Williams and could reach out to see if anyone in her group is interested.

@sebastiandig : who was it you mentioned in today's meeting that is using binder? Perhaps ey knows others who may be interested?

**Comment by sebastiandig** [comment]
@7yl4r Nancy Williams is experienced in binder. She was going to use it to host a jupyter environment for class.
